import { Product, Category, Order, MonthlyData, Transaction, StoreProfile } from '../types';

export const fallbackCategories: Category[] = [
  { id: 1, name: 'Giày Sneaker & Thể Thao', slug: 'giay-sneaker-the-thao', productCount: 7 },
  { id: 2, name: 'Thời Trang Streetwear & Áo Khoác', slug: 'thoi-trang-streetwear-ao-khoac', productCount: 6 },
  { id: 3, name: 'Quần & Phụ Kiện Thời Trang', slug: 'quan-phu-kien-thoi-trang', productCount: 6 },
  { id: 4, name: 'Gia Dụng & Đời Sống', slug: 'gia-dung-doi-song', productCount: 1 }
];

export const fallbackProducts: Product[] = [
  {
    id: 101,
    categoryId: 1,
    categoryName: 'Giày Sneaker & Thể Thao',
    name: 'Giày Adidas Samba OG Classic White Black',
    slug: 'giay-adidas-samba-og-classic',
    sku: 'ADI-SAMBA-01',
    collectionName: 'Adidas Originals Terrace',
    description: 'Giày thể thao Adidas Samba OG phiên bản Classic phối màu trắng đen cổ điển, chất liệu da thật cao cấp kết hợp mũi T-toe da lộn.',
    basePrice: 2790000,
    originalPrice: 3200000,
    discountPercent: 12,
    imageUrl: '/img/products/adidas-samba.jpg',
    stockQuantity: 45,
    stockStatus: 'IN_STOCK',
    material: 'Full-grain leather with suede overlay',
    countryOfOrigin: 'Việt Nam / Germany',
    rating: 4.9,
    reviewCount: 86
  },
  {
    id: 102,
    categoryId: 2,
    categoryName: 'Thời Trang Streetwear & Áo Khoác',
    name: 'Áo Khoác Nỉ Adidas Sakura Special Edition',
    slug: 'ao-khoac-ni-adidas-sakura',
    sku: 'ADI-SAKURA-02',
    collectionName: 'Adidas Sakura 2024',
    description: 'Áo khoác nỉ Adidas phối họa tiết thêu hoa anh đào độc đáo, chất nỉ bông dày dặn giữ ấm tối ưu.',
    basePrice: 2190000,
    originalPrice: 2500000,
    discountPercent: 12,
    imageUrl: '/img/products/adidas-sakura-hoodie.jpg',
    stockQuantity: 30,
    stockStatus: 'IN_STOCK',
    material: '100% Cotton Fleece',
    countryOfOrigin: 'Việt Nam',
    rating: 4.8,
    reviewCount: 54
  },
  {
    id: 103,
    categoryId: 1,
    categoryName: 'Giày Sneaker & Thể Thao',
    name: 'Giày Balenciaga Track 4.0 Tan/Beige',
    slug: 'giay-balenciaga-track-40-tan-beige',
    sku: 'BAL-TRK-03',
    collectionName: 'Balenciaga Track Series',
    description: 'Sneaker Balenciaga Track 4.0 phối màu tan beige phong cách chunky hầm hố, đệm lót êm ái.',
    basePrice: 24500000,
    originalPrice: 26000000,
    discountPercent: 6,
    imageUrl: '/img/products/balenciaga-track-beige.jpg',
    stockQuantity: 12,
    stockStatus: 'IN_STOCK',
    material: 'Mesh and Nylon multi-layer',
    countryOfOrigin: 'Italy / China',
    rating: 5.0,
    reviewCount: 42
  },
  {
    id: 104,
    categoryId: 1,
    categoryName: 'Giày Sneaker & Thể Thao',
    name: 'Giày Balenciaga Track Thug Edition Black',
    slug: 'giay-balenciaga-track-thug-edition-black',
    sku: 'BAL-TRK-04',
    collectionName: 'Balenciaga Street Noir',
    description: 'Phiên bản Balenciaga Track Thug đen cực ngầu phong cách streetwear, chi tiết phản quang độc đáo.',
    basePrice: 23900000,
    originalPrice: 25500000,
    discountPercent: 6,
    imageUrl: '/img/products/balenciaga-track-black.jpg',
    stockQuantity: 8,
    stockStatus: 'LOW_STOCK',
    material: 'High-tech composite & mesh',
    countryOfOrigin: 'Italy',
    rating: 4.9,
    reviewCount: 68
  },
  {
    id: 105,
    categoryId: 3,
    categoryName: 'Quần & Phụ Kiện Thời Trang',
    name: 'Quần Nỉ Balenciaga Paris Sweatpants White',
    slug: 'quan-ni-balenciaga-paris-sweatpants-white',
    sku: 'BAL-PNT-05',
    collectionName: 'Balenciaga Paris Wardrobe',
    description: 'Quần nỉ ống rộng Balenciaga Paris chữ thêu dọc ống quần màu trắng, phong cách oversize thoải mái.',
    basePrice: 16500000,
    originalPrice: 18000000,
    discountPercent: 8,
    imageUrl: '/img/products/balenciaga-track-street.jpg',
    stockQuantity: 15,
    stockStatus: 'IN_STOCK',
    material: '100% French Terry Organic Cotton',
    countryOfOrigin: 'Portugal',
    rating: 4.7,
    reviewCount: 31
  },
  {
    id: 106,
    categoryId: 1,
    categoryName: 'Giày Sneaker & Thể Thao',
    name: 'Giày Sneaker Gucci Ace Web Leather',
    slug: 'giay-sneaker-gucci-ace-web-leather',
    sku: 'GUC-ACE-06',
    collectionName: 'Gucci Icons',
    description: 'Sneaker Gucci Ace da bò thật phối sọc xanh đỏ truyền thống của nhà mốt Kering.',
    basePrice: 18900000,
    originalPrice: 21000000,
    discountPercent: 10,
    imageUrl: '/img/products/gucci-sneaker.jpg',
    stockQuantity: 20,
    stockStatus: 'IN_STOCK',
    material: 'Calfskin Leather, Rubber sole',
    countryOfOrigin: 'Made in Italy',
    rating: 5.0,
    reviewCount: 112
  },
  {
    id: 107,
    categoryId: 3,
    categoryName: 'Quần & Phụ Kiện Thời Trang',
    name: 'Kính Mát Gucci Double G Rectangular Cream Gold',
    slug: 'kinh-mat-gucci-double-g-rectangular-cream-gold',
    sku: 'GUC-SUN-07',
    collectionName: 'Gucci Eyewear',
    description: 'Kính mát Gucci gọng chữ nhật màu kem đính logo Double G mạ vàng 18K sang trọng.',
    basePrice: 11500000,
    originalPrice: 13000000,
    discountPercent: 11,
    imageUrl: '/img/products/gucci-runway.jpg',
    stockQuantity: 18,
    stockStatus: 'IN_STOCK',
    material: 'Acetate cao cấp, kim loại mạ vàng',
    countryOfOrigin: 'Made in Italy',
    rating: 4.9,
    reviewCount: 59
  },
  {
    id: 108,
    categoryId: 1,
    categoryName: 'Giày Sneaker & Thể Thao',
    name: 'Giày Thể Thao Nike Men\'s Summer Sneaker 2024',
    slug: 'giay-the-thao-nike-summer-sneaker-2024',
    sku: 'NIK-SMR-08',
    collectionName: 'Nike Air Running',
    description: 'Mẫu giày chạy bộ mùa hè Nike thiết kế thoáng khí, đế Air đàn hồi cao cho trải nghiệm thể thao mượt mà.',
    basePrice: 3250000,
    originalPrice: 3700000,
    discountPercent: 12,
    imageUrl: '/img/Nike men\'s summer sneaker (men shoe collection for 2024).jpg',
    stockQuantity: 50,
    stockStatus: 'IN_STOCK',
    material: 'Flyknit and Air Zoom Sole',
    countryOfOrigin: 'Việt Nam',
    rating: 4.8,
    reviewCount: 94
  },
  {
    id: 109,
    categoryId: 2,
    categoryName: 'Thời Trang Streetwear & Áo Khoác',
    name: 'Áo Khoác Denim Balenciaga Oversized Ripped Jacket',
    slug: 'ao-khoac-denim-balenciaga-oversized-ripped',
    sku: 'BAL-JKT-09',
    collectionName: 'Balenciaga Runway',
    description: 'Áo khoác bò Balenciaga rách phong cách grunge bụi bặm, form rộng oversize thời thượng.',
    basePrice: 28500000,
    originalPrice: 32000000,
    discountPercent: 11,
    imageUrl: '/img/products/balenciaga-ripped-jacket.jpg',
    stockQuantity: 7,
    stockStatus: 'LOW_STOCK',
    material: '100% Japanese Selvedge Denim',
    countryOfOrigin: 'Japan / France',
    rating: 4.9,
    reviewCount: 28
  },
  {
    id: 110,
    categoryId: 1,
    categoryName: 'Giày Sneaker & Thể Thao',
    name: 'Giày Sneaker Puma Fall Footwear Retro Edition',
    slug: 'giay-sneaker-puma-fall-footwear-retro',
    sku: 'PUM-RET-10',
    collectionName: 'Puma Classic',
    description: 'Giày thể thao Puma phiên bản mùa thu cổ điển da lộn mềm mại, form chuẩn châu Á.',
    basePrice: 1850000,
    originalPrice: 2100000,
    discountPercent: 12,
    imageUrl: '/img/products/puma-shoes-fall.jpg',
    stockQuantity: 40,
    stockStatus: 'IN_STOCK',
    material: 'Suede & Rubber Gum Sole',
    countryOfOrigin: 'Indonesia',
    rating: 4.6,
    reviewCount: 77
  },
  {
    id: 111,
    categoryId: 3,
    categoryName: 'Quần & Phụ Kiện Thời Trang',
    name: 'Túi Xách Nữ Gucci Dionysus GG Supreme Mini',
    slug: 'tui-xach-nu-gucci-dionysus-gg-supreme-mini',
    sku: 'GUC-DIO-11',
    collectionName: 'Gucci Dionysus',
    description: 'Túi đeo chéo Dionysus họa tiết GG Supreme với khóa đầu hổ đặc trưng mạ bạc cổ điển.',
    basePrice: 32000000,
    originalPrice: 35000000,
    discountPercent: 8,
    imageUrl: '/img/products/gucci-sneaker.jpg',
    stockQuantity: 10,
    stockStatus: 'IN_STOCK',
    material: 'GG Supreme Canvas & Da Taupe Suede',
    countryOfOrigin: 'Made in Italy',
    rating: 5.0,
    reviewCount: 49
  },
  {
    id: 112,
    categoryId: 2,
    categoryName: 'Thời Trang Streetwear & Áo Khoác',
    name: 'Áo Thun Gucci Blade Print Cotton T-Shirt',
    slug: 'ao-thun-gucci-blade-print-cotton-tshirt',
    sku: 'GUC-TSH-12',
    collectionName: 'Gucci Ready-to-Wear',
    description: 'Áo phông cotton hữu cơ in logo lưỡi dao Gucci Blade phong cách sắc nét, co giãn 4 chiều.',
    basePrice: 12500000,
    originalPrice: 14000000,
    discountPercent: 10,
    imageUrl: '/img/products/gucci-collection.jpg',
    stockQuantity: 25,
    stockStatus: 'IN_STOCK',
    material: '100% Organic Heavyweight Cotton',
    countryOfOrigin: 'Made in Italy',
    rating: 4.8,
    reviewCount: 63
  },
  {
    id: 113,
    categoryId: 3,
    categoryName: 'Quần & Phụ Kiện Thời Trang',
    name: 'Mũ Lưỡi Trai Balenciaga Cap Embroidery Black',
    slug: 'mu-luoi-trai-balenciaga-cap-embroidery-black',
    sku: 'BAL-CAP-13',
    collectionName: 'Balenciaga Accessories',
    description: 'Mũ lưỡi trai Balenciaga thêu chữ nổi mặt trước, quai dán điều chỉnh phía sau tiện lợi.',
    basePrice: 8900000,
    originalPrice: 9800000,
    discountPercent: 9,
    imageUrl: '/img/products/108930884729091904.jpg',
    stockQuantity: 22,
    stockStatus: 'IN_STOCK',
    material: '100% Cotton Twill',
    countryOfOrigin: 'Italy',
    rating: 4.7,
    reviewCount: 38
  },
  {
    id: 114,
    categoryId: 3,
    categoryName: 'Quần & Phụ Kiện Thời Trang',
    name: 'Thắt Lưng Da Gucci Double G Buckle Leather Belt',
    slug: 'that-lung-da-gucci-double-g-buckle',
    sku: 'GUC-BLT-14',
    collectionName: 'Gucci Belts',
    description: 'Thắt lưng da bê trơn mặt khóa kim loại chữ G lồng nhau màu vàng kim cổ điển bản 3cm.',
    basePrice: 11900000,
    originalPrice: 13000000,
    discountPercent: 8,
    imageUrl: '/img/products/12173861489974136.jpg',
    stockQuantity: 16,
    stockStatus: 'IN_STOCK',
    material: 'Calfskin Leather, Antiqued Brass Buckle',
    countryOfOrigin: 'Made in Italy',
    rating: 4.9,
    reviewCount: 85
  },
  {
    id: 115,
    categoryId: 1,
    categoryName: 'Giày Sneaker & Thể Thao',
    name: 'Giày Sneaker Gucci Rhyton Logo Leather',
    slug: 'giay-sneaker-gucci-rhyton-logo-leather',
    sku: 'GUC-RHY-15',
    collectionName: 'Gucci Rhyton',
    description: 'Sneaker Gucci Rhyton da ngà đế dày chunky in logo Gucci vintage phong cách thập niên 90.',
    basePrice: 22500000,
    originalPrice: 25000000,
    discountPercent: 10,
    imageUrl: '/img/products/20758848278669764.jpg',
    stockQuantity: 14,
    stockStatus: 'IN_STOCK',
    material: 'Supple Ivory Leather',
    countryOfOrigin: 'Made in Italy',
    rating: 4.9,
    reviewCount: 51
  },
  {
    id: 116,
    categoryId: 2,
    categoryName: 'Thời Trang Streetwear & Áo Khoác',
    name: 'Áo Hoodie Balenciaga Back Logo Print Grey',
    slug: 'ao-hoodie-balenciaga-back-logo-grey',
    sku: 'BAL-HOD-16',
    collectionName: 'Balenciaga Streetwear',
    description: 'Áo hoodie nỉ xám in logo Balenciaga mặt sau, mũ trùm sâu, form rộng drop-shoulder.',
    basePrice: 19500000,
    originalPrice: 22000000,
    discountPercent: 11,
    imageUrl: '/img/products/267823509086088024.jpg',
    stockQuantity: 18,
    stockStatus: 'IN_STOCK',
    material: 'Cotton Fleece Heavyweight',
    countryOfOrigin: 'Portugal',
    rating: 4.8,
    reviewCount: 44
  },
  {
    id: 117,
    categoryId: 3,
    categoryName: 'Quần & Phụ Kiện Thời Trang',
    name: 'Ví Cầm Tay Gucci GG Marmont Leather Wallet',
    slug: 'vi-cam-tay-gucci-gg-marmont-leather',
    sku: 'GUC-WLT-17',
    collectionName: 'Gucci Marmont',
    description: 'Ví nữ dáng dài chần bông họa tiết chevron da bò tự nhiên kèm logo Double G mạ vàng.',
    basePrice: 14800000,
    originalPrice: 16500000,
    discountPercent: 10,
    imageUrl: '/img/products/298926494039684010.jpg',
    stockQuantity: 12,
    stockStatus: 'IN_STOCK',
    material: 'Matelassé Chevron Leather',
    countryOfOrigin: 'Made in Italy',
    rating: 5.0,
    reviewCount: 72
  },
  {
    id: 118,
    categoryId: 1,
    categoryName: 'Giày Sneaker & Thể Thao',
    name: 'Giày Sneaker Balenciaga Defender Chunky Tyre',
    slug: 'giay-sneaker-balenciaga-defender-tyre',
    sku: 'BAL-DEF-18',
    collectionName: 'Balenciaga Footwear',
    description: 'Sneaker Balenciaga Defender đế lốp xe siêu hầm hố, thiết kế tương lai đột phá.',
    basePrice: 26500000,
    originalPrice: 29000000,
    discountPercent: 8,
    imageUrl: '/img/products/34551122141164310.jpg',
    stockQuantity: 6,
    stockStatus: 'LOW_STOCK',
    material: 'Technical Fabric & Rubber Sole',
    countryOfOrigin: 'China',
    rating: 4.7,
    reviewCount: 33
  },
  {
    id: 119,
    categoryId: 2,
    categoryName: 'Thời Trang Streetwear & Áo Khoác',
    name: 'Áo Khoác Gió Balenciaga Windbreaker Zip Jacket',
    slug: 'ao-khoac-gio-balenciaga-windbreaker',
    sku: 'BAL-WND-19',
    collectionName: 'Balenciaga Outerwear',
    description: 'Áo khoác dù chống nước Balenciaga khóa kéo 2 chiều, dây rút gấu áo điều chỉnh phong cách thể thao.',
    basePrice: 2100000,
    originalPrice: 2400000,
    discountPercent: 12,
    imageUrl: '/img/products/420734790192673506.jpg',
    stockQuantity: 15,
    stockStatus: 'IN_STOCK',
    material: 'Water-repellent Technical Ripstop',
    countryOfOrigin: 'Italy',
    rating: 4.8,
    reviewCount: 29
  },
  {
    id: 120,
    categoryId: 4,
    categoryName: 'Gia Dụng & Đời Sống',
    name: 'Gối Tựa Sofa Aethelgard Luxury Velvet Cushion',
    slug: 'goi-tua-sofa-aethelgard-luxury-velvet',
    sku: 'AET-HOM-20',
    collectionName: 'Aethelgard Maison',
    description: 'Gối tựa nhung cao cấp thêu họa tiết gia huy Aethelgard mạ chỉ bạc, ruột lông vũ êm ái.',
    basePrice: 1450000,
    originalPrice: 1800000,
    discountPercent: 19,
    imageUrl: '/img/products/fashion-mood-board.jpg',
    stockQuantity: 35,
    stockStatus: 'IN_STOCK',
    material: 'Premium Silk Velvet & Feather fill',
    countryOfOrigin: 'Việt Nam',
    rating: 4.9,
    reviewCount: 57
  }
];

export const fallbackOrders: Order[] = [
  {
    id: 1,
    orderCode: 'AG-2024-7890',
    customerName: 'Esther Howard',
    customerEmail: 'john.doe@example.com',
    customerPhone: '+1 (555) 123-4567',
    shippingAddress: '123 Main Street, New York, NY 10001, United States',
    paymentMethod: 'Thẻ Tín Dụng (Visa ending in 4242)',
    status: 'SHIPPED',
    statusLabel: 'Đang Vận Chuyển',
    createdAt: '2026-01-15 10:20 AM',
    carrier: 'FedEx Logistics',
    trackingCode: '789012345678',
    estimatedDelivery: 'January 20, 2026',
    lastUpdateLocation: 'Package departed from facility in NEW YORK, NY (Hub)',
    progressStep: 3,
    subtotal: 30400000,
    shippingCharge: 60000,
    taxes: 2432000,
    discount: 1000000,
    totalAmount: 31892000,
    items: [
      {
        id: 1,
        productName: 'Giày Sneaker Gucci Ace Web Leather',
        specs: 'Color: White/Green-Red Stripe | Size: 41 EU',
        imageUrl: '/img/products/gucci-sneaker.jpg',
        price: 18900000,
        quantity: 1,
        subtotal: 18900000
      },
      {
        id: 2,
        productName: 'Kính Mát Gucci Double G Rectangular Cream Gold',
        specs: 'Color: Cream Gold | Category: Accessories',
        imageUrl: '/img/products/gucci-runway.jpg',
        price: 11500000,
        quantity: 1,
        subtotal: 11500000
      }
    ]
  },
  {
    id: 2,
    orderCode: 'AG-2024-7891',
    customerName: 'Cameron Williamson',
    customerEmail: 'cameron.w@example.com',
    customerPhone: '+84 901 234 567',
    shippingAddress: 'Tòa nhà Keangnam Landmark 72, Phạm Hùng, Cầu Giấy, Hà Nội',
    paymentMethod: 'Ví MoMo / Chuyển khoản QR',
    status: 'CONFIRMED',
    statusLabel: 'Đã Xác Nhận',
    createdAt: '2026-09-17 14:15 PM',
    carrier: 'FedEx Logistics',
    trackingCode: '789123456789',
    estimatedDelivery: 'September 25, 2026',
    lastUpdateLocation: 'Trung tâm phân phối Hà Nội tiếp nhận',
    progressStep: 2,
    subtotal: 2790000,
    shippingCharge: 35000,
    taxes: 223200,
    discount: 0,
    totalAmount: 3048200,
    items: [
      {
        id: 3,
        productName: 'Giày Adidas Samba OG Classic White Black',
        specs: 'Color: White/Black | Size: 42 EU',
        imageUrl: '/img/products/adidas-samba.jpg',
        price: 2790000,
        quantity: 1,
        subtotal: 2790000
      }
    ]
  }
];

export const fallbackMatrixData: MonthlyData[] = [
  { month: 'JAN', existingUsers: 4, newUsers: 3, valTotal: '14k' },
  { month: 'FEB', existingUsers: 5, newUsers: 4, valTotal: '18k' },
  { month: 'MAR', existingUsers: 6, newUsers: 6, valTotal: '24k' },
  { month: 'APR', existingUsers: 5, newUsers: 7, valTotal: '26k' },
  { month: 'MAY', existingUsers: 7, newUsers: 10, valTotal: '34k' },
  { month: 'JUN', existingUsers: 8, newUsers: 14, valTotal: '56k', isActive: true, newText: '38k', existText: '18k' },
  { month: 'JUL', existingUsers: 6, newUsers: 8, valTotal: '30k' },
  { month: 'AUG', existingUsers: 5, newUsers: 6, valTotal: '22k' },
  { month: 'SEP', existingUsers: 4, newUsers: 5, valTotal: '19k' },
  { month: 'OCT', existingUsers: 6, newUsers: 7, valTotal: '27k' },
  { month: 'NOV', existingUsers: 5, newUsers: 8, valTotal: '28k' },
  { month: 'DEC', existingUsers: 7, newUsers: 9, valTotal: '32k' }
];

export const fallbackTransactions: Transaction[] = [
  { id: '#04910', customer: 'Ryan Korsgaard', product: 'Ergo Office Chair', status: 'Success', qty: 12, unitPrice: '$3,450', total: '$41,400' },
  { id: '#04911', customer: 'Madelyn Lubin', product: 'Sunset Desk 02', status: 'Success', qty: 20, unitPrice: '$2,980', total: '$59,200' },
  { id: '#04912', customer: 'Abram Bergson', product: 'Eco Bookshelf', status: 'Pending', qty: 22, unitPrice: '$1,750', total: '$75,900' },
  { id: '#04913', customer: 'Phillip Mango', product: 'Green Leaf Desk', status: 'Refunded', qty: 24, unitPrice: '$1,950', total: '$19,500' },
  { id: '#04914', customer: 'Esther Howard', product: 'Giày Sneaker Gucci Ace Leather', status: 'Success', qty: 2, unitPrice: '$1,250', total: '$2,500' },
  { id: '#04915', customer: 'Darrell Steward', product: 'Túi Gucci Dionysus Supreme', status: 'Success', qty: 1, unitPrice: '$2,850', total: '$2,850' },
  { id: '#04916', customer: 'Cameron Williamson', product: 'Adidas Samba OG Classic', status: 'Success', qty: 4, unitPrice: '$180', total: '$720' }
];

export const fallbackStores: StoreProfile[] = [
  {
    id: 1,
    storeCode: 'VN_HN_01',
    brandId: 'gucci',
    storeName: 'Gucci Tràng Tiền Plaza',
    storeType: 'Flagship Boutique',
    city: 'Hà Nội',
    country: 'Việt Nam',
    address: 'Tầng 1 & 2, Tràng Tiền Plaza, 24 Hai Bà Trưng, P. Tràng Tiền, Q. Hoàn Kiếm',
    phone: '+84 24 3936 9999',
    email: 'trangtien.boutique@gucci.com',
    operatingHours: 'T2 - T6: 09:30 - 21:30 | T7 - CN: 09:30 - 22:00',
    latitude: 21.0253,
    longitude: 105.8544,
    services: [
      'Đặt hẹn chuyên gia riêng (Private Appointment)',
      'Dập chữ cá nhân hóa (Hot Stamping)',
      'Bảo dưỡng đồ da cao cấp',
      'Phòng chờ VIP Lounge',
      'Đỗ xe Valet',
      'Hoàn thuế VAT Refund'
    ],
    categories: [
      'Túi xách cao cấp',
      'Sneaker & Giày dép',
      'Trang sức & Đồng hồ',
      'Đồ da nhỏ',
      'Thời trang may sẵn'
    ],
    imageUrl: '/img/products/gucci-runway.jpg',
    storeUrl: 'https://www.gucci.com/us/en/store/trang-tien-plaza'
  },
  {
    id: 2,
    storeCode: 'VN_SG_01',
    brandId: 'gucci',
    storeName: 'Gucci Sheraton Saigon',
    storeType: 'Luxury Hotel Boutique',
    city: 'TP. Hồ Chí Minh',
    country: 'Việt Nam',
    address: 'Khách sạn Sheraton Saigon, 88 Đồng Khởi, P. Bến Nghé, Quận 1',
    phone: '+84 28 3827 6688',
    email: 'sheraton.saigon@gucci.com',
    operatingHours: 'T2 - CN: 10:00 - 21:00',
    latitude: 10.7769,
    longitude: 106.7032,
    services: [
      'Mua sắm tại phòng Suite',
      'Stylist tư vấn phong cách riêng',
      'Dập chữ cá nhân hóa',
      'Bảo hành quốc tế'
    ],
    categories: [
      'Túi xách biểu tượng Jackie & Marmont',
      'Giày Loafer & Sneaker',
      'Thắt lưng da Double G'
    ],
    imageUrl: '/img/products/sample-velora.jpg',
    storeUrl: 'https://www.gucci.com/us/en/store/sheraton-saigon'
  },
  {
    id: 3,
    storeCode: 'VN_SG_02',
    brandId: 'gucci',
    storeName: 'Gucci Union Square',
    storeType: 'Mall Flagship',
    city: 'TP. Hồ Chí Minh',
    country: 'Việt Nam',
    address: 'Union Square Shopping Center, 171 Đồng Khởi, Quận 1',
    phone: '+84 28 3824 5566',
    email: 'unionsquare.hcm@gucci.com',
    operatingHours: 'T2 - CN: 09:30 - 22:00',
    latitude: 10.7761,
    longitude: 106.7018,
    services: [
      'Boutique 2 tầng phong cách Milan',
      'Bảo dưỡng trang sức kim cương',
      'Chăm sóc sản phẩm White Glove'
    ],
    categories: [
      'Ready-to-Wear',
      'Fine Jewelry',
      'Gucci Décor',
      'Giày cao cấp'
    ],
    imageUrl: '/img/products/sample-nextgen.jpg',
    storeUrl: 'https://www.gucci.com/us/en/store/union-square'
  }
];
